version: '3.8'
services:
  HUXbackend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    command: npm run dev 